//#pragma once


// NGS_BUILD_LIB_CONFIG_ENABLE_INLINE
// NGS_BUILD_LIB_CONFIG_VERSION

#if NGS_BUILD_LIB_CONFIG_ENABLE_INLINE
#
#	define NGS_BUILD_LIB_INLINE_MODIFIER inline
#
#else
#
#	define NGS_BUILD_LIB_INLINE_MODIFIER
#
#endif

#ifdef NGS_BUILD_LIB_CONFIG_VERSION
#
#	define NGS_BUILD_LIB_VERSION NGS_LIB_CONFIG_VERSION
#
#else
#
#	define NGS_BUILD_LIB_VERSION (0,0,0)
#
#endif